openapi: 3.0.1
info:
  title: API de Carritos
  description: Documentación de la API para manejar carritos de compra
  version: 1.0.0
paths:
  /api/carts:
    post:
      summary: Crear un nuevo carrito
      tags:
        - Carritos
      responses:
        '201':
          description: Carrito creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error del servidor

  /api/carts/{cid}:
    get:
      summary: Obtener productos de un carrito por ID
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Productos del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Carrito no encontrado
        '500':
          description: Error del servidor
    put:
      summary: Actualizar productos en un carrito
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCart'
      responses:
        '200':
          description: Carrito actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Error del servidor
    delete:
      summary: Vaciar un carrito
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Carrito vaciado
        '500':
          description: Error del servidor

  /api/carts/{cid}/product/{pid}:
    post:
      summary: Agregar un producto al carrito
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Producto agregado al carrito
        '500':
          description: Error del servidor
    delete:
      summary: Eliminar un producto del carrito
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto eliminado del carrito
        '500':
          description: Error del servidor
    put:
      summary: Actualizar la cantidad de un producto en el carrito
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Cantidad del producto actualizada
        '500':
          description: Error del servidor

  /api/carts/{cid}/purchase:
    post:
      summary: Finalizar compra
      tags:
        - Carritos
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Compra finalizada
          content:
            application/json:
              schema:
                type: object
                properties:
                  productosNoDisponibles:
                    type: array
                    items:
                      type: string
        '500':
          description: Error del servidor

components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
        totalPrice:
          type: number
    UpdateCart:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/CartItem'
    CartItem:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
