openapi: 3.0.1
info:
  title: API de Productos
  description: Documentación de la API para manejar productos
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Obtener productos
      tags:
        - Productos
      parameters:
        - name: limit
          in: query
          description: Límite de productos por página
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          description: Número de página
          schema:
            type: integer
            default: 1
        - name: sort
          in: query
          description: Criterio de ordenación
          schema:
            type: string
        - name: query
          in: query
          description: Filtro de búsqueda
          schema:
            type: string
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error al obtener los productos
    post:
      summary: Agregar un nuevo producto
      tags:
        - Productos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Producto agregado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Error al agregar el producto

  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto obtenido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Producto no encontrado
        '500':
          description: Error al obtener el producto
    put:
      summary: Actualizar un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '200':
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '500':
          description: Error al actualizar el producto
    delete:
      summary: Eliminar un producto por ID
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Producto eliminado
        '500':
          description: Error al eliminar el producto

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        owner:
          type: string
    NewProduct:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        owner:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
